name: Create GitHub Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Only make a GitHub release if the commit message contains a simple semver string (e.g., '1.2.3')
      - name: Check for Simple Semver in Commit Message
        run: |
          commit_message=$(git log --format=%B -n 1 ${{ github.sha }})
          simple_semver_pattern="^v?[0-9]+\.[0-9]+\.[0-9]+$"
          if ! [[ "$commit_message" =~ $simple_semver_pattern ]]; then
            echo "Commit message does not contain a simple semver string (e.g., '1.2.3'). This probably is not a release. Aborting..."
            exit 1
          fi
      
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref }}
          commit: ${{ github.sha }}
          name: ${{ github.ref_name }}
          body: "New release of the public repository"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
